apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-sync-app
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/limanalhassan/microservices-argoCD.git
    path: application
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: app-spaces
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


