apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-sync-app
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/limanalhassan/microservices-argoCD.git
    path: prometheus-grafana
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


